//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsNum.Xmj.API.Res {


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsNum.Xmj.API.Res.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 运费模板ID 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityFreightTemplate_ID_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityFreightTemplate_ID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运费模板 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityFreightTemplate_Name_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityFreightTemplate_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10% 即打9折 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_BulkDiscount_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_BulkDiscount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批发折扣率 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_BulkDiscount_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_BulkDiscount_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起批量 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_BulkOrder_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_BulkOrder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CategoryID 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_CategoryID_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_CategoryID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品分类ID 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_CategoryID_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_CategoryID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品详情 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_Detail_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_Detail_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运费模板ID 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_FreightTemplateID_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_FreightTemplateID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品图片 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_ImageUrls_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_ImageUrls_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否动态图 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_IsImageDynamic_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_IsImageDynamic_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否加水印 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_IsImageWatermark_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_IsImageWatermark_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否打包出售 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_IsPackageSell_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_IsPackageSell_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主关键字 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_Keyword_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_Keyword_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字1 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_Keyword1_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_Keyword1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字2 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_Keyword2_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_Keyword2_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多少个一包 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_LotNum_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_LotNum_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CM 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_PackageHeight_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_PackageHeight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包裹高 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_PackageHeight_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_PackageHeight_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CM 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_PackageLength_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_PackageLength_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包裹长度 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_PackageLength_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_PackageLength_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KG 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_PackageWeight_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_PackageWeight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包裹重量 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_PackageWeight_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_PackageWeight_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CM 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_PackageWidth_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_PackageWidth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包裹宽度 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_PackageWidth_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_PackageWidth_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认30天 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_PeriodOfValidity_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_PeriodOfValidity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品有限期 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_PeriodOfValidity_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_PeriodOfValidity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一口价 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_Price_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_Price_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品分组 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_ProductGroup_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_ProductGroup_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_ProductName_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_ProductName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_StockUpPeriod_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_StockUpPeriod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备货期 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_StockUpPeriod_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_StockUpPeriod_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProduct_Unit_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProduct_Unit_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品分组ID 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProductGroup_ID_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProductGroup_ID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品分组 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIEntityProductGroup_Name_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIEntityProductGroup_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderID 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsOrderFindByID_OrderID_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsOrderFindByID_OrderID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单号 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsOrderFindByID_OrderID_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsOrderFindByID_OrderID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderID 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsOrderMsgListByOrderId_OrderID_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsOrderMsgListByOrderId_OrderID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单ID 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsOrderMsgListByOrderId_OrderID_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsOrderMsgListByOrderId_OrderID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateBegin 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsOrderQueryList_CreateBegin_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsOrderQueryList_CreateBegin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单创建时间 起 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsOrderQueryList_CreateBegin_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsOrderQueryList_CreateBegin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateEnd 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsOrderQueryList_CreateEnd_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsOrderQueryList_CreateEnd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单创建时间 止 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsOrderQueryList_CreateEnd_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsOrderQueryList_CreateEnd_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认值为1 Page 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsOrderQueryList_Page_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsOrderQueryList_Page_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第几页 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsOrderQueryList_Page_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsOrderQueryList_Page_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每页数据最大50笔,可不填 PageSize 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsOrderQueryList_PageSize_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsOrderQueryList_PageSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分页大小 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsOrderQueryList_PageSize_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsOrderQueryList_PageSize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认为全部 OrderStatus 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsOrderQueryList_Status_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsOrderQueryList_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单状态 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsOrderQueryList_Status_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsOrderQueryList_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片银行的分组ID GroupID 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankGroupList_GroupID_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankGroupList_GroupID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组ID 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankGroupList_GroupID_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankGroupList_GroupID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填写文件路径后,会自动带入 FileName 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankUploadImage_FileName_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankUploadImage_FileName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankUploadImage_FileName_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankUploadImage_FileName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地图片文件路径 FilePath 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankUploadImage_FilePath_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankUploadImage_FilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片文件路径 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankUploadImage_FilePath_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankUploadImage_FilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片银行分组ID,不填即为默认 GroupID 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankUploadImage_GroupID_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankUploadImage_GroupID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组ID 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankUploadImage_GroupID_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankUploadImage_GroupID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填写文件路径后,会自动带入 UploadData 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankUploadImage_UploadData_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankUploadImage_UploadData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片字节数组 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankUploadImage_UploadData_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankUploadImage_UploadData_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填写路径后,会自动带入 FileName 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankUploadTempImage_FileName_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankUploadTempImage_FileName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankUploadTempImage_FileName_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankUploadTempImage_FileName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地图片路径 FilePath 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankUploadTempImage_FilePath_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankUploadTempImage_FilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片路径 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankUploadTempImage_FilePath_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankUploadTempImage_FilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填写路径后,会自动带入 UploadData 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankUploadTempImage_UploadData_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankUploadTempImage_UploadData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字节数组 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsPhotoBankUploadTempImage_UploadData_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsPhotoBankUploadTempImage_UploadData_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductID 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsProductFindById_ProductID_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsProductFindById_ProductID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品ID 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsProductFindById_ProductID_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsProductFindById_ProductID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsProductGetProductGroup_Page_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsProductGetProductGroup_Page_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第几页 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsProductGetProductGroup_Page_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsProductGetProductGroup_Page_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductDetail 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsProductNewProduct_ProductDetail_Description {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsProductNewProduct_ProductDetail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品详情 的本地化字符串。
        /// </summary>
        public static string AsNumAliexpressAPIMethodsProductNewProduct_ProductDetail_DisplayName {
            get {
                return ResourceManager.GetString("AsNumAliexpressAPIMethodsProductNewProduct_ProductDetail_DisplayName", resourceCulture);
            }
        }
    }
}
