// <auto-generated />
namespace AsNum.Xmj.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class LogisticFee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LogisticFee));
        
        string IMigrationMetadata.Id
        {
            get { return "201502211508229_LogisticFee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
