// <auto-generated />
namespace AsNum.Xmj.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddLogisticService : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLogisticService));
        
        string IMigrationMetadata.Id
        {
            get { return "201509190243297_AddLogisticService"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
