// <auto-generated />
namespace AsNum.Xmj.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class BuyerLevel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BuyerLevel));
        
        string IMigrationMetadata.Id
        {
            get { return "201508121415125_BuyerLevel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
