// <auto-generated />
namespace AsNum.Xmj.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class BuyerLevel1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BuyerLevel1));
        
        string IMigrationMetadata.Id
        {
            get { return "201508121433050_BuyerLevel1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
